# Generated by Django 4.2.5 on 2023-09-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litlelemonresturant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(default='images/images_2.png', upload_to='images')),
            ],
        ),
    ]
