# Generated by Django 4.2.5 on 2023-09-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litlelemonresturant', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=100),
        ),
    ]
